site_name: vQTL
site_description: vQTL Workflow Documentation
repo_url: https://github.com/MRCopeland74/stapleton_lab/tree/master/docs
theme: readthedocs
edit_uri: https://github.com/MRCopeland74/stapleton_lab/tree/master/docs
nav:
- Home: 'index.md'
- Project Overview: 'Project Overview.md'
- WorkFlow:
    - Getting Started: 'Using R.md'
    - Data: 'Data.md'
    - vQTL Analysis': 'vQTL Analysis.md'
    - qPCR Analysis': 'qPCR Analysis.md'
    - Workflow: 'Workflow.md'
- Tutorials:
    - Introduction to GitHub and Project Set-up: 'Using GitHub.md'
    - Introduction to scanonevar(): 'Using Scanonevar.md'
    - Getting Started with High Performance Computing: 'Using HPC.md'
    - Jobs on HPC: 'Jobs on HPC.md'
    - Launcher Module: 'Launcher Module.md'
    - Reminders and Useful Commands: 'Reminders and Useful Commands.md'
    - Updating the Docs: 'Updating the Docs.md'
site_author: 'Austin Gratton and Michael Copeland'
