data = read.csv("../../../../../Downloads/ManchingStressData_Covar.csv")
data2 = read.csv("Manching_interactive_model.csv")
data3 = read.csv("Manching_additive_model.csv")
data4 = read.csv("Manching_interactive_model2.csv")
setwd("/Users/michaelcopeland/Stapleton/Copeland/stapleton_lab/vQTL/")
intOneVar <- read_rds("intOneVar.rds")
plot(intOneVar)
