library(qtl)
library(vqtl)
library(purrr)
library(readr)
library(dplyr)
library(tidyverse)
setwd("/Users/michaelcopeland/Stapleton/Copeland/stapleton_lab/vQTL/")
data = read.csv("ManchingStressData_Covar.csv")
data2 = read.csv("Manching_interactive_model.csv")
data3 = read.csv("Manching_additive_model.csv")
data4 = read.csv("Manching_interactive_model2.csv")
lw = read.csv("Manching_interactive_lw_model.csv")
addlw = read.csv("Manching_additive_AddLowWater_model.csv")
assnorm = read.csv("Manching_additive_NORM_model.csv")
intNorm = read.csv("Manching_interactive_NORM_model.csv")
data4cross <-read.cross(file = "ManchingStressData_Covar.csv")
intOneVar <- read_rds("intOneVar.rds")
intOneVar1 <- read_rds("intOneVar_int.rds")
intOneVarlw <- read_rds("intOneVar_lw.rds")
intnormrds = read_rds("intOneVar_NORM.rds")
addOneVar <- read_rds("addOneVar.rds")
addOneVar1 <- read_rds("addOneVar_NORM.rds")
adlowrds <- read_rds("addOneVar_AddLowWater.rds")
vqtl::effects_over_genome_plot(intOneVar$result)
vqtl::effects_over_genome_plot(intOneVar1, data4cross)
vqtl::effects_over_genome_plot(intOneVarlw)
vqtl::effects_over_genome_plot(addOneVar)
vqtl::effects_over_genome_plot(addOneVar1)
vqtl::effects_over_genome_plot(intnormrds)
plot(intOneVar1
 #    ,     tests_to_plot = "mQTL", chrs = "1"
     )
plot(adlowrds
         ,     tests_to_plot = "mQTL"
     #, chrs = "1"
)

intenv <- read_rds("intenv.rds")
intlw <- read_rds("intenv.rds")
intall <- read_rds("intall.rds")
scan1 <- read_rds("scan1.rds")
