library(qtl)
library(vqtl)
library(purrr)
library(readr)
library(dplyr)
library(tidyverse)
setwd("/Users/michaelcopeland/Stapleton/Copeland/stapleton_lab/vQTL/")
data = read.csv("ManchingStressData_Covar.csv")
data2 = read.csv("Manching_interactive_model.csv")
data3 = read.csv("Manching_additive_model.csv")
data4 = read.csv("Manching_interactive_model2.csv")
lw = read.csv("Manching_interactive_lw_model.csv")

intOneVar <- read_rds("intOneVar.rds")
vqtl::effects_over_genome_plot(intOneVar,intOneVar$result$chr)
vqtl::mean_var_plot_model_based(data)
